In [7]:
!wget -q "https://raw.githubusercontent.com/gustavo-hnunes/An-lise-de-Dados-Ebac/main/salary_data.csv" -o salarios.csv

In [17]:
import pandas as pd
import numpy as np

In [50]:
data = pd.read_csv('salary_data.csv', sep=',')
data.isnull().any()

country_name      False
continent_name    False
wage_span         False
median_salary     False
average_salary    False
lowest_salary     False
highest_salary    False
dtype: bool

In [30]:
data

,country_name,continent_name,wage_span,median_salary,average_salary,lowest_salary,highest_salary
0,Afghanistan,Asia,Monthly,853.740000,1001.150000,252.530000,4460.970000
1,Aland Islands,Europe,Monthly,3319.240000,3858.350000,972.520000,17124.740000
2,Albania,Europe,Monthly,832.840000,956.920000,241.220000,4258.490000
3,Algeria,Africa,Monthly,1148.840000,1308.810000,330.110000,5824.180000
4,American Samoa,Oceania,Monthly,1390.000000,1570.000000,400.000000,6980.000000
...,...,...,...,...,...,...,...
216,Virgin Islands (US),North America,Monthly,2380.000000,2710.000000,680.000000,12000.000000
217,Western Sahara,Africa,Monthly,908.560000,1011.670000,254.860000,4503.890000
218,Yemen,Asia,Monthly,120.980000,133.360000,33.620000,594.930000
219,Zambia,Africa,Monthly,0.261335,0.285524,0.072092,1.271103
220,Zimbabwe,Africa,Monthly,555.402040,602.376350,151.423050,2674.772000

In [51]:
median_array = np.asarray(data['median_salary'].astype('float').tolist())
average_array = np.asarray(data['average_salary'].astype('float').tolist())
lowest_array = np.asarray(data['lowest_salary'].astype('float').tolist())
highest_array = np.asarray(data['highest_salary'].astype('float').tolist())

In [52]:
median_media = data['median_salary'].mean()
average_media = data['average_salary'].mean()
lowest_media = data['lowest_salary'].mean()
highest_media = data['highest_salary'].mean()

median_desvio = data['median_salary'].std()
average_desvio = data['average_salary'].std()
lowest_desvio = data['lowest_salary'].std()
highest_desvio = data['highest_salary'].std()

data['median_salary_std'] = data['median_salary'].apply(lambda salario_mediano: (salario_mediano - median_media) / median_desvio)
data['average_salary_std'] = data['average_salary'].apply(lambda salario_medio: (salario_medio - average_media) / average_desvio)
data['lowest_salary_std'] = data['lowest_salary'].apply(lambda salario_menor: (salario_menor - lowest_media) / lowest_desvio)
data['highest_salary_std'] = data['highest_salary'].apply(lambda salario_maior: (salario_maior - highest_media) / highest_desvio)

data.head()

,country_name,continent_name,wage_span,median_salary,average_salary,lowest_salary,highest_salary,median_salary_std,average_salary_std,lowest_salary_std,highest_salary_std
0,Afghanistan,Asia,Monthly,853.74,1001.15,252.53,4460.97,-0.555996,-0.534583,-0.532371,-0.533303
1,Aland Islands,Europe,Monthly,3319.24,3858.35,972.52,17124.74,0.952224,1.022110,0.999284,1.022403
2,Albania,Europe,Monthly,832.84,956.92,241.22,4258.49,-0.568781,-0.558681,-0.556431,-0.558177
3,Algeria,Africa,Monthly,1148.84,1308.81,330.11,5824.18,-0.375475,-0.366960,-0.367332,-0.365836
4,American Samoa,Oceania,Monthly,1390.00,1570.00,400.00,6980.00,-0.227950,-0.224656,-0.218654,-0.223847

In [53]:
from os import spawnl
data['continent_name'].drop_duplicates()

continent_mapper = {
    "Asia": 'ASI',
    "Europe": 'EUR',
    "Africa": 'AFR',
    "Oceania": 'OCE',
    "Caribbean": 'CAR',
    "South America": 'SAM',
    "Central America": 'CAM',
    "North America": 'NAM',
    "Northern America": 'NAM'
}

data['continent_nom'] = data['continent_name'].apply(lambda continent: continent_mapper[continent])
data.head()

span_mapper = {
    "Weekly": 1,
    "Monthly": 2,
    "Semester": 3,
    "Yearly": 4
    }

data['wage_span_nom'] = data['wage_span'].apply(lambda span: span_mapper[span])

In [54]:
data = data.drop(['continent_name', 'median_salary', 'lowest_salary', 'highest_salary', 'average_salary', 'wage_span'], axis=1)
data = data.reindex(columns=['country_name', 'continent_nom', 'wage_span_nom', 'median_salary_std', 'average_salary_std', 'lowest_salary_std', 'highest_salary_std'])
data.head()

,country_name,continent_nom,wage_span_nom,median_salary_std,average_salary_std,lowest_salary_std,highest_salary_std
0,Afghanistan,ASI,2,-0.555996,-0.534583,-0.532371,-0.533303
1,Aland Islands,EUR,2,0.952224,1.022110,0.999284,1.022403
2,Albania,EUR,2,-0.568781,-0.558681,-0.556431,-0.558177
3,Algeria,AFR,2,-0.375475,-0.366960,-0.367332,-0.365836
4,American Samoa,OCE,2,-0.227950,-0.224656,-0.218654,-0.223847